package com.db.alipay.entity;

public class AliPayData {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alipay.id
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alipay.starttime
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private Long starttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alipay.endtime
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private Long endtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alipay.appid
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private String appid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alipay.totalfee
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private Integer totalfee;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alipay.sign
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private String sign;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alipay.status
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private String status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alipay.bundleid
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private String bundleid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alipay.id
     *
     * @return the value of alipay.id
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alipay.id
     *
     * @param id the value for alipay.id
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alipay.starttime
     *
     * @return the value of alipay.starttime
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public Long getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alipay.starttime
     *
     * @param starttime the value for alipay.starttime
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void setStarttime(Long starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alipay.endtime
     *
     * @return the value of alipay.endtime
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public Long getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alipay.endtime
     *
     * @param endtime the value for alipay.endtime
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void setEndtime(Long endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alipay.appid
     *
     * @return the value of alipay.appid
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alipay.appid
     *
     * @param appid the value for alipay.appid
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alipay.totalfee
     *
     * @return the value of alipay.totalfee
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public Integer getTotalfee() {
        return totalfee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alipay.totalfee
     *
     * @param totalfee the value for alipay.totalfee
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void setTotalfee(Integer totalfee) {
        this.totalfee = totalfee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alipay.sign
     *
     * @return the value of alipay.sign
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alipay.sign
     *
     * @param sign the value for alipay.sign
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alipay.status
     *
     * @return the value of alipay.status
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alipay.status
     *
     * @param status the value for alipay.status
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alipay.bundleid
     *
     * @return the value of alipay.bundleid
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public String getBundleid() {
        return bundleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alipay.bundleid
     *
     * @param bundleid the value for alipay.bundleid
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void setBundleid(String bundleid) {
        this.bundleid = bundleid;
    }
}