package com.db.applepay.dao;

import com.db.applepay.entity.ApplePayData;
import com.db.applepay.entity.ApplePayDataExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class ApplePayDataDAOImpl implements ApplePayDataDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public ApplePayDataDAOImpl(SqlMapClient sqlMapClient)
	{
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public void insert(ApplePayData record) throws SQLException
	{
		sqlMapClient.insert("applepay.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public int updateByPrimaryKey(ApplePayData record) throws SQLException
	{
		int rows = sqlMapClient.update(
				"applepay.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public int updateByPrimaryKeySelective(ApplePayData record)
			throws SQLException
	{
		int rows = sqlMapClient.update(
				"applepay.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public List selectByExample(ApplePayDataExample example)
			throws SQLException
	{
		List list = sqlMapClient.queryForList(
				"applepay.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public ApplePayData selectByPrimaryKey(String id) throws SQLException
	{
		ApplePayData key = new ApplePayData();
		key.setId(id);
		ApplePayData record = (ApplePayData) sqlMapClient.queryForObject(
				"applepay.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public int deleteByExample(ApplePayDataExample example) throws SQLException
	{
		int rows = sqlMapClient.delete(
				"applepay.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public int deleteByPrimaryKey(String id) throws SQLException
	{
		ApplePayData key = new ApplePayData();
		key.setId(id);
		int rows = sqlMapClient.delete(
				"applepay.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public int countByExample(ApplePayDataExample example) throws SQLException
	{
		Integer count = (Integer) sqlMapClient.queryForObject(
				"applepay.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public int updateByExampleSelective(ApplePayData record,
			ApplePayDataExample example) throws SQLException
	{
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"applepay.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public int updateByExample(ApplePayData record, ApplePayDataExample example)
			throws SQLException
	{
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"applepay.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table applepay
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	private static class UpdateByExampleParms extends ApplePayDataExample
	{
		private Object record;

		public UpdateByExampleParms(Object record, ApplePayDataExample example)
		{
			super(example);
			this.record = record;
		}

		public Object getRecord()
		{
			return record;
		}
	}
}