package com.db.alikey.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AliKeyDataExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public AliKeyDataExample()
	{
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	protected AliKeyDataExample(AliKeyDataExample example)
	{
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public void setOrderByClause(String orderByClause)
	{
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public String getOrderByClause()
	{
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public List getOredCriteria()
	{
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public void or(Criteria criteria)
	{
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public Criteria createCriteria()
	{
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0)
		{
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	protected Criteria createCriteriaInternal()
	{
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public void clear()
	{
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public static class Criteria
	{
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria()
		{
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid()
		{
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue()
		{
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue()
		{
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue()
		{
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue()
		{
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition)
		{
			if (condition == null)
			{
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property)
		{
			if (value == null)
			{
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property)
		{
			if (values == null || values.size() == 0)
			{
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property)
		{
			if (value1 == null || value2 == null)
			{
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andBundleidIsNull()
		{
			addCriterion("bundleid is null");
			return this;
		}

		public Criteria andBundleidIsNotNull()
		{
			addCriterion("bundleid is not null");
			return this;
		}

		public Criteria andBundleidEqualTo(String value)
		{
			addCriterion("bundleid =", value, "bundleid");
			return this;
		}

		public Criteria andBundleidNotEqualTo(String value)
		{
			addCriterion("bundleid <>", value, "bundleid");
			return this;
		}

		public Criteria andBundleidGreaterThan(String value)
		{
			addCriterion("bundleid >", value, "bundleid");
			return this;
		}

		public Criteria andBundleidGreaterThanOrEqualTo(String value)
		{
			addCriterion("bundleid >=", value, "bundleid");
			return this;
		}

		public Criteria andBundleidLessThan(String value)
		{
			addCriterion("bundleid <", value, "bundleid");
			return this;
		}

		public Criteria andBundleidLessThanOrEqualTo(String value)
		{
			addCriterion("bundleid <=", value, "bundleid");
			return this;
		}

		public Criteria andBundleidLike(String value)
		{
			addCriterion("bundleid like", value, "bundleid");
			return this;
		}

		public Criteria andBundleidNotLike(String value)
		{
			addCriterion("bundleid not like", value, "bundleid");
			return this;
		}

		public Criteria andBundleidIn(List values)
		{
			addCriterion("bundleid in", values, "bundleid");
			return this;
		}

		public Criteria andBundleidNotIn(List values)
		{
			addCriterion("bundleid not in", values, "bundleid");
			return this;
		}

		public Criteria andBundleidBetween(String value1, String value2)
		{
			addCriterion("bundleid between", value1, value2, "bundleid");
			return this;
		}

		public Criteria andBundleidNotBetween(String value1, String value2)
		{
			addCriterion("bundleid not between", value1, value2, "bundleid");
			return this;
		}

		public Criteria andSelleridIsNull()
		{
			addCriterion("sellerid is null");
			return this;
		}

		public Criteria andSelleridIsNotNull()
		{
			addCriterion("sellerid is not null");
			return this;
		}

		public Criteria andSelleridEqualTo(String value)
		{
			addCriterion("sellerid =", value, "sellerid");
			return this;
		}

		public Criteria andSelleridNotEqualTo(String value)
		{
			addCriterion("sellerid <>", value, "sellerid");
			return this;
		}

		public Criteria andSelleridGreaterThan(String value)
		{
			addCriterion("sellerid >", value, "sellerid");
			return this;
		}

		public Criteria andSelleridGreaterThanOrEqualTo(String value)
		{
			addCriterion("sellerid >=", value, "sellerid");
			return this;
		}

		public Criteria andSelleridLessThan(String value)
		{
			addCriterion("sellerid <", value, "sellerid");
			return this;
		}

		public Criteria andSelleridLessThanOrEqualTo(String value)
		{
			addCriterion("sellerid <=", value, "sellerid");
			return this;
		}

		public Criteria andSelleridLike(String value)
		{
			addCriterion("sellerid like", value, "sellerid");
			return this;
		}

		public Criteria andSelleridNotLike(String value)
		{
			addCriterion("sellerid not like", value, "sellerid");
			return this;
		}

		public Criteria andSelleridIn(List values)
		{
			addCriterion("sellerid in", values, "sellerid");
			return this;
		}

		public Criteria andSelleridNotIn(List values)
		{
			addCriterion("sellerid not in", values, "sellerid");
			return this;
		}

		public Criteria andSelleridBetween(String value1, String value2)
		{
			addCriterion("sellerid between", value1, value2, "sellerid");
			return this;
		}

		public Criteria andSelleridNotBetween(String value1, String value2)
		{
			addCriterion("sellerid not between", value1, value2, "sellerid");
			return this;
		}
	}
}