package com.db.alikey.entity;

public class AliKeyDataWithBLOBs extends AliKeyData {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alikey.pubkey
     *
     * @abatorgenerated Mon Oct 16 16:35:17 CST 2017
     */
    private String pubkey;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column alikey.prikey
     *
     * @abatorgenerated Mon Oct 16 16:35:17 CST 2017
     */
    private String prikey;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alikey.pubkey
     *
     * @return the value of alikey.pubkey
     *
     * @abatorgenerated Mon Oct 16 16:35:17 CST 2017
     */
    public String getPubkey() {
        return pubkey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alikey.pubkey
     *
     * @param pubkey the value for alikey.pubkey
     *
     * @abatorgenerated Mon Oct 16 16:35:17 CST 2017
     */
    public void setPubkey(String pubkey) {
        this.pubkey = pubkey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column alikey.prikey
     *
     * @return the value of alikey.prikey
     *
     * @abatorgenerated Mon Oct 16 16:35:17 CST 2017
     */
    public String getPrikey() {
        return prikey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column alikey.prikey
     *
     * @param prikey the value for alikey.prikey
     *
     * @abatorgenerated Mon Oct 16 16:35:17 CST 2017
     */
    public void setPrikey(String prikey) {
        this.prikey = prikey;
    }
}