package com.db.alikey.entity;

public class AliKeyData {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column alikey.bundleid
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	private String bundleid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column alikey.sellerid
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	private String sellerid;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column alikey.bundleid
	 * @return  the value of alikey.bundleid
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public String getBundleid()
	{
		return bundleid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column alikey.bundleid
	 * @param bundleid  the value for alikey.bundleid
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public void setBundleid(String bundleid)
	{
		this.bundleid = bundleid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column alikey.sellerid
	 * @return  the value of alikey.sellerid
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public String getSellerid()
	{
		return sellerid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column alikey.sellerid
	 * @param sellerid  the value for alikey.sellerid
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public void setSellerid(String sellerid)
	{
		this.sellerid = sellerid;
	}
}