package com.db.alikey.dao;

import com.db.alikey.entity.AliKeyData;
import com.db.alikey.entity.AliKeyDataExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import com.db.alikey.entity.AliKeyDataWithBLOBs;

public class AliKeyDataDAOImpl implements AliKeyDataDAO {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public AliKeyDataDAOImpl(SqlMapClient sqlMapClient)
	{
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public void insert(AliKeyDataWithBLOBs record) throws SQLException
	{
		sqlMapClient.insert("alikey.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int updateByPrimaryKey(AliKeyData record) throws SQLException
	{
		int rows = sqlMapClient.update(
				"alikey.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int updateByPrimaryKey(AliKeyDataWithBLOBs record)
			throws SQLException
	{
		int rows = sqlMapClient.update(
				"alikey.abatorgenerated_updateByPrimaryKeyWithBLOBs", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int updateByPrimaryKeySelective(AliKeyDataWithBLOBs record)
			throws SQLException
	{
		int rows = sqlMapClient.update(
				"alikey.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public List selectByExampleWithoutBLOBs(AliKeyDataExample example)
			throws SQLException
	{
		List list = sqlMapClient.queryForList(
				"alikey.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public List selectByExampleWithBLOBs(AliKeyDataExample example)
			throws SQLException
	{
		List list = sqlMapClient.queryForList(
				"alikey.abatorgenerated_selectByExampleWithBLOBs", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public AliKeyDataWithBLOBs selectByPrimaryKey(String bundleid)
			throws SQLException
	{
		AliKeyData key = new AliKeyData();
		key.setBundleid(bundleid);
		AliKeyDataWithBLOBs record = (AliKeyDataWithBLOBs) sqlMapClient
				.queryForObject("alikey.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int deleteByExample(AliKeyDataExample example) throws SQLException
	{
		int rows = sqlMapClient.delete(
				"alikey.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int deleteByPrimaryKey(String bundleid) throws SQLException
	{
		AliKeyData key = new AliKeyData();
		key.setBundleid(bundleid);
		int rows = sqlMapClient.delete(
				"alikey.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int countByExample(AliKeyDataExample example) throws SQLException
	{
		Integer count = (Integer) sqlMapClient.queryForObject(
				"alikey.abatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int updateByExampleSelective(AliKeyDataWithBLOBs record,
			AliKeyDataExample example) throws SQLException
	{
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"alikey.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int updateByExample(AliKeyDataWithBLOBs record,
			AliKeyDataExample example) throws SQLException
	{
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"alikey.abatorgenerated_updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	public int updateByExample(AliKeyData record, AliKeyDataExample example)
			throws SQLException
	{
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"alikey.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	private static class UpdateByExampleParms extends AliKeyDataExample
	{
		private Object record;

		public UpdateByExampleParms(Object record, AliKeyDataExample example)
		{
			super(example);
			this.record = record;
		}

		public Object getRecord()
		{
			return record;
		}
	}
}