package com.db.alikey.dao;

import com.db.alikey.entity.AliKeyData;
import com.db.alikey.entity.AliKeyDataExample;
import java.sql.SQLException;
import java.util.List;
import com.db.alikey.entity.AliKeyDataWithBLOBs;

public interface AliKeyDataDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	void insert(AliKeyDataWithBLOBs record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int updateByPrimaryKey(AliKeyData record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int updateByPrimaryKey(AliKeyDataWithBLOBs record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int updateByPrimaryKeySelective(AliKeyDataWithBLOBs record)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	List selectByExampleWithoutBLOBs(AliKeyDataExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	List selectByExampleWithBLOBs(AliKeyDataExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	AliKeyDataWithBLOBs selectByPrimaryKey(String bundleid) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int deleteByExample(AliKeyDataExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int deleteByPrimaryKey(String bundleid) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int countByExample(AliKeyDataExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int updateByExampleSelective(AliKeyDataWithBLOBs record,
			AliKeyDataExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int updateByExample(AliKeyDataWithBLOBs record, AliKeyDataExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table alikey
	 * @abatorgenerated  Mon Oct 16 16:35:17 CST 2017
	 */
	int updateByExample(AliKeyData record, AliKeyDataExample example)
			throws SQLException;
}