package com.db.alipay.dao;

import com.db.alipay.entity.AliPayData;
import com.db.alipay.entity.AliPayDataExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class AliPayDataDAOImpl implements AliPayDataDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public AliPayDataDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public void insert(AliPayData record) throws SQLException {
        sqlMapClient.insert("alipay.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public int updateByPrimaryKey(AliPayData record) throws SQLException {
        int rows = sqlMapClient.update("alipay.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public int updateByPrimaryKeySelective(AliPayData record) throws SQLException {
        int rows = sqlMapClient.update("alipay.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public List selectByExample(AliPayDataExample example) throws SQLException {
        List list = sqlMapClient.queryForList("alipay.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public AliPayData selectByPrimaryKey(String id) throws SQLException {
        AliPayData key = new AliPayData();
        key.setId(id);
        AliPayData record = (AliPayData) sqlMapClient.queryForObject("alipay.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public int deleteByExample(AliPayDataExample example) throws SQLException {
        int rows = sqlMapClient.delete("alipay.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public int deleteByPrimaryKey(String id) throws SQLException {
        AliPayData key = new AliPayData();
        key.setId(id);
        int rows = sqlMapClient.delete("alipay.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public int countByExample(AliPayDataExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("alipay.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public int updateByExampleSelective(AliPayData record, AliPayDataExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("alipay.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    public int updateByExample(AliPayData record, AliPayDataExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("alipay.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table alipay
     *
     * @abatorgenerated Mon Oct 16 12:07:10 CST 2017
     */
    private static class UpdateByExampleParms extends AliPayDataExample {
        private Object record;

        public UpdateByExampleParms(Object record, AliPayDataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}