package com.db.wxpay.entity;

public class WxPayData {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wxpay.id
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wxpay.starttime
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private Long starttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wxpay.endtime
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private Long endtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wxpay.appid
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private String appid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wxpay.totalfee
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private Integer totalfee;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wxpay.sign
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private String sign;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wxpay.status
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private String status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column wxpay.bundleid
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private String bundleid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wxpay.id
     *
     * @return the value of wxpay.id
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wxpay.id
     *
     * @param id the value for wxpay.id
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wxpay.starttime
     *
     * @return the value of wxpay.starttime
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public Long getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wxpay.starttime
     *
     * @param starttime the value for wxpay.starttime
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void setStarttime(Long starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wxpay.endtime
     *
     * @return the value of wxpay.endtime
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public Long getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wxpay.endtime
     *
     * @param endtime the value for wxpay.endtime
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void setEndtime(Long endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wxpay.appid
     *
     * @return the value of wxpay.appid
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wxpay.appid
     *
     * @param appid the value for wxpay.appid
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wxpay.totalfee
     *
     * @return the value of wxpay.totalfee
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public Integer getTotalfee() {
        return totalfee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wxpay.totalfee
     *
     * @param totalfee the value for wxpay.totalfee
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void setTotalfee(Integer totalfee) {
        this.totalfee = totalfee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wxpay.sign
     *
     * @return the value of wxpay.sign
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wxpay.sign
     *
     * @param sign the value for wxpay.sign
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wxpay.status
     *
     * @return the value of wxpay.status
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wxpay.status
     *
     * @param status the value for wxpay.status
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column wxpay.bundleid
     *
     * @return the value of wxpay.bundleid
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public String getBundleid() {
        return bundleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column wxpay.bundleid
     *
     * @param bundleid the value for wxpay.bundleid
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void setBundleid(String bundleid) {
        this.bundleid = bundleid;
    }
}