package com.db.applepay.entity;

public class ApplePayData {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column applepay.id
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column applepay.time
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	private Long time;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column applepay.bundleid
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	private String bundleid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column applepay.totalfee
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	private Integer totalfee;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column applepay.status
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	private String status;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column applepay.id
	 * @return  the value of applepay.id
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column applepay.id
	 * @param id  the value for applepay.id
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public void setId(String id)
	{
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column applepay.time
	 * @return  the value of applepay.time
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public Long getTime()
	{
		return time;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column applepay.time
	 * @param time  the value for applepay.time
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public void setTime(Long time)
	{
		this.time = time;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column applepay.bundleid
	 * @return  the value of applepay.bundleid
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public String getBundleid()
	{
		return bundleid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column applepay.bundleid
	 * @param bundleid  the value for applepay.bundleid
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public void setBundleid(String bundleid)
	{
		this.bundleid = bundleid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column applepay.totalfee
	 * @return  the value of applepay.totalfee
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public Integer getTotalfee()
	{
		return totalfee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column applepay.totalfee
	 * @param totalfee  the value for applepay.totalfee
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public void setTotalfee(Integer totalfee)
	{
		this.totalfee = totalfee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column applepay.status
	 * @return  the value of applepay.status
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column applepay.status
	 * @param status  the value for applepay.status
	 * @abatorgenerated  Mon Oct 16 11:23:17 CST 2017
	 */
	public void setStatus(String status)
	{
		this.status = status;
	}
}