package com.db.wxpay.dao;

import com.db.wxpay.entity.WxPayData;
import com.db.wxpay.entity.WxPayDataExample;
import java.sql.SQLException;
import java.util.List;

public interface WxPayDataDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    void insert(WxPayData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    int updateByPrimaryKey(WxPayData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    int updateByPrimaryKeySelective(WxPayData record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    List selectByExample(WxPayDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    WxPayData selectByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    int deleteByExample(WxPayDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    int deleteByPrimaryKey(String id) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    int countByExample(WxPayDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    int updateByExampleSelective(WxPayData record, WxPayDataExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    int updateByExample(WxPayData record, WxPayDataExample example) throws SQLException;
}