package com.db.wxpay.dao;

import com.db.wxpay.entity.WxPayData;
import com.db.wxpay.entity.WxPayDataExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class WxPayDataDAOImpl implements WxPayDataDAO {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public WxPayDataDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public void insert(WxPayData record) throws SQLException {
        sqlMapClient.insert("wxpay.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public int updateByPrimaryKey(WxPayData record) throws SQLException {
        int rows = sqlMapClient.update("wxpay.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public int updateByPrimaryKeySelective(WxPayData record) throws SQLException {
        int rows = sqlMapClient.update("wxpay.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public List selectByExample(WxPayDataExample example) throws SQLException {
        List list = sqlMapClient.queryForList("wxpay.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public WxPayData selectByPrimaryKey(String id) throws SQLException {
        WxPayData key = new WxPayData();
        key.setId(id);
        WxPayData record = (WxPayData) sqlMapClient.queryForObject("wxpay.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public int deleteByExample(WxPayDataExample example) throws SQLException {
        int rows = sqlMapClient.delete("wxpay.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public int deleteByPrimaryKey(String id) throws SQLException {
        WxPayData key = new WxPayData();
        key.setId(id);
        int rows = sqlMapClient.delete("wxpay.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public int countByExample(WxPayDataExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("wxpay.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public int updateByExampleSelective(WxPayData record, WxPayDataExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("wxpay.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    public int updateByExample(WxPayData record, WxPayDataExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("wxpay.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table wxpay
     *
     * @abatorgenerated Mon Oct 16 11:29:12 CST 2017
     */
    private static class UpdateByExampleParms extends WxPayDataExample {
        private Object record;

        public UpdateByExampleParms(Object record, WxPayDataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}